dist: bionic
language: java
jdk: openjdk8
before_install:
  - sudo apt-get update
  - sudo ./scripts/ubuntu_18.04_dependencies.sh
  # TODO: somehow this java setup doesn't work on travis, see build log
  # https://travis-ci.org/github/jschaul/wire-audio-video-signaling/jobs/691080459
  # - sudo apt-get purge --auto-remove openjdk*
  # - sudo apt-get install -y openjdk-8-jdk openjdk-8-jre
  - java -version
  - sudo java -version
  - jdk_switcher use openjdk8
  - java -version
  - sudo java -version
  # - sudo update-java-alternatives --jre-headless --jre --plugin -s java-1.8.0-openjdk-amd64 || true
install:
  - cd webrtc && travis_wait 50 ./scripts/build.sh
  - cd webrtc && ./scripts/package.sh
  - touch contrib/webrtc/webrtc_m79.local_ios.zip
  - touch contrib/webrtc/webrtc_m79.local_osx.zip
  - ./prepare.sh
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local zcall
