dist: bionic
language: C
before_install:
  - sudo apt-get update
  - sudo ./scripts/ubuntu_18.04_dependencies.sh
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives --jre-headless --jre --plugin -s java-1.8.0-openjdk-amd64 || true
install:
  - cd webrtc && ./scripts/build.sh && ./scripts/package.sh
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local zcall
