dist: bionic
language: java
# travis has special jdk handling ('jdk: openjdk8').
# In case you want to follow these steps outside travis, you can try with the following instead:
# - sudo apt-get install -y openjdk-8-jdk openjdk-8-jre
# - sudo update-java-alternatives --jre-headless --jre --plugin -s java-1.8.0-openjdk-amd64 || true
jdk: openjdk8
before_install:
  - sudo apt-get update
  - sudo ./scripts/ubuntu_18.04_dependencies.sh
  - java -version
install:
  - cd webrtc && travis_wait 50 ./scripts/build.sh
  - cd webrtc && ./scripts/package.sh
  - touch contrib/webrtc/webrtc_m79.local_ios.zip
  - touch contrib/webrtc/webrtc_m79.local_osx.zip
  - ./prepare.sh
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local
  - export PATH="$HOME/.cargo/bin:$PATH"; make WEBRTC_VER=m79.local zcall
